import type { LanguageCode } from "./LanguageCode";

export type Strings = Record<
  LanguageCode,
  {
    locale: string;
    heading: string;
    subtitle: string;
    addExpensesHint: string;
    noData: string;
    monthlyExpensesTitle: (month: string) => string;
    monthlyIncomeTitle: (month: string) => string;
    tableHeaders: {
      name: string;
      cadence: string;
      amount: string;
      converted: (month: string, currency: string) => string;
    };
    cadenceLabel: { monthly: string; yearly: string };
    totalsTitle: (currency: string) => string;
    trendTitle: (currency: string) => string;
    waterfallLabels: { income: string; expense: string; balance: string };
    ofIncome: string;
    pieTitle: (month: string) => string;
    settingsTitle: string;
    baseCurrency: string;
    baseCurrencyDesc: string;
    monthsToShow: string;
    monthsToShowDesc: string;
    notesPath: string;
    notesPathDesc: string;
    manualExpenseCategories: string;
    manualExpenseCategoriesDesc: string;
    expensesList: string;
    incomesList: string;
    add: string;
    edit: string;
    delete: string;
    since: string;
    expenseModalTitle: string;
    incomeModalTitle: string;
    name: string;
    amount: string;
    currency: string;
    cadence: string;
    cadenceDesc: string;
    start: string;
    startDesc: string;
    save: string;
    missingFields: string;
    duplicateName: string;
    manualExpenseInvalidDate: string;
    manualExpenseEmptyCategory: string;
    manualExpenseInvalidAmount: string;
    monthlySavingsInvalidMonth: string;
    monthlySavingsInvalidAmount: string;
    monthlySavingsDuplicateCurrency: string;
    monthlySavingsMissingBalances: string;
    month: string;
    total: string;
    language: string;
    dashboardPageTitle: string;
    monthlyPageTitle: string;
    monthlyPageSubtitle: string;
    monthlyPageEmptyStateTitle: string;
    monthlyPageEmptyStateDescription: string;
    monthlyPageDiagnosticsTitle: string;
    monthlyPageInvalidExpenseNotes: (count: number) => string;
    monthlyPageInvalidSavingsNotes: (count: number) => string;
    monthlyPageDuplicateExpenseNotes: (count: number) => string;
    monthlyPageDuplicateSavingsNotes: (count: number) => string;
    previousPage: string;
    nextPage: string;
    monthFilterLabel: string;
    yearFilterLabel: string;
    categoriesFilterLabel: string;
    allCategoriesLabel: string;
    addExpenseAction: string;
    addSavingsAction: string;
    manualExpenseModalTitle: string;
    manualExpenseDate: string;
    manualExpenseCategory: string;
    manualExpenseCategoryPlaceholder: string;
    monthlySavingsModalTitle: string;
    monthlySavingsMonth: string;
    monthlySavingsCurrency: string;
    monthlySavingsAmount: string;
    monthlySavingsAddRow: string;
    monthlySavingsRemoveRow: string;
    monthlyPageExpensesTitle: string;
    monthlyPageSavingsTitle: string;
    monthlyPageNoExpenses: string;
    monthlyPageNoSavings: string;
    monthlyPageNoCategories: string;
    monthlyPageTotalExpenses: (currency: string) => string;
    monthlyPageSelectedMonth: string;
    monthlyPageExpenseBreakdownTitle: (currency: string) => string;
    monthlyPageSavingsBalancesTitle: string;
    monthlyPageSavingsBaseTotalTitle: (currency: string) => string;
    monthlyPageSavingsGrowthTitle: (currency: string) => string;
    monthlyPageNoExpenseAnalytics: string;
    monthlyPageNoSavingsAnalytics: string;
    monthlyPageConvertedFromLabel: (currency: string, baseCurrency: string) => string;
    monthlyPageGrowthTooltipDelta: string;
    monthlyPageSavingsCurrenciesCount: string;
  }
>;
